version: '3'

services:
  dashboard:
    build: ..
    ports:
      - "5000:5000"

  server1:
    build: ..
    command: python services/server.py

  server2:
    build: ..
    command: python services/server.py